version: '3.8'

services:
  db:
    image: postgres:15
    container_name: behavior-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trigger-db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
