version: '3.8'

services:
  db:
    image: postgres:16
    container_name: behavior-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trigger-db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"   # RabbitMQ 기본 포트 AMQP
      - "15672:15672" # RabbitMQ 관리 콘솔 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
