spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trigger-db
    username: devuser
    password: devpass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html