spring:
  profiles:
    active: local # 기본 실행 시 local 활성화. Render 에서는 dev 로 덮어씀
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false # Swagger UI 충돌 방지
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
        simple:
          default-requeue-rejected: false # 재시도 방지
          acknowledge-mode: AUTO # AUTO, MANUAL, NONE

# JWT
jwt:
  secret: thisIsMySuperSecretKeyThatIsAtLeast32CharsLong!