# 워크플로 이름
name: CI

# 어떤 이벤트에 반응할지 설정
on:
  push:
    branches:
      - main      # main에 push될 때 (배포 전 최종 테스트)
      - dev       # dev에 push될 때 (통합 테스트)
  pull_request:
    branches:
      - dev       # feat/* 브랜치 → dev PR 생성 시 테스트 트리거

# 실제 실행될 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest            # GitHub Actions에서 사용할 가상 환경

    steps:
      - name: Checkout code           # GitHub 리포지토리에서 소스코드를 가져옴
        uses: actions/checkout@v4

      - name: Set up JDK 17           # Java 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'     # OpenJDK 배포판
          java-version: '17'

      - name: Grant execute permission for gradlew   # gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Build with Gradle without test         # 테스트 생략 빌드 (개발 중 빠른 피드백용)
        run: ./gradlew build -x test --no-daemon

      - name: Run Tests                              # 테스트 실행 (이후 단계에서 조건 분기 가능)
        run: ./gradlew test --no-daemon
